export const types = {
  SET_CURRENT_CITY: 'SET_CURRENT_CITY',
  SET_CURRENT_DISTRICT: 'SET_CURRENT_DISTRICT',
  SET_LOCATION: 'SET_LOCATION',
  SET_STORES: 'SET_STORES',
  SET_KEYWORDS: 'SET_KEYWORDS',
  SET_SHOWMODAL: 'SET_SHOWMODAL',
  SET_LIGHTBOXSID: 'SET_LIGHTBOXSID',
  FETCH_LOCATION: 'FETCH_LOCATION',
  FETCH_STORES: 'FETCH_STORES'
}
