export const types = {
  SET_CURRENT_CITY: 'SET_CURRENT_CITY',
  SET_CURRENT_DISTRICT: 'SET_CURRENT_DISTRICT',
  SET_LOCATION: 'SET_LOCATION',
  SET_STORES: 'SET_STORES',
  FETCH_LOCATION: 'FETCH_LOCATION',
  FETCH_STORES: 'FETCH_STORES'
}
